### ISSUE TITLE
Marketplace fails to start (Windows10)

### ISSUE THREAD

**Issue by kangoala** [particl/particl-desktop#1791]
Having had two functioning Particl Testnet Installations 3.0.0-RC-test002 or test003 on two different Windows10 64-bit PCs. When updating on test004 only one remained functioning while on the other PC it always fails to start the marketplace application. I tried to uninstall the marketplace app, but also after re-installing RC-test004 the marketplace still fail to start.

**Comment by bacoinin** [comment]
@kangoala If you had RC003 or RC 002 installed prior installing the RC004 then make sure you have followed the instructions below before running the RC004
https://github.com/particl/particl-desktop/releases/tag/v3.0.0-RC-test004

**Comment by kangoala** [comment]
Yep, I did the same way as with my first PC. Then I deleted the complete "Particl Desktop testnet" folder and the "Particl marketplace" folder (but also without success). Currently I deleted all Particl folders and are doing a complete fresh installation (including downloading of the whole testnet blockchain). However, this will now take quite a while before I can further comment to this topic. :-)

**Comment by zaSmilingIdiot** [comment]
> Then I deleted the complete "Particl Desktop testnet" folder and the "Particl marketplace" folder (but also without success)

You'll also need to remove the wallets that the particl-market created previously. The instructions for doing so are included in the link provided in https://github.com/particl/particl-desktop/issues/1791#issuecomment-882094259 .
Removing the particl-market created wallet is a necessary step when removing the particl-market created folders, because the particl-market stores specific references to the wallets it creates.

This is currrently a manual process, and something that'll hopefully be addressed in a future version.

**Comment by zaSmilingIdiot** [comment]
Closing this for now, as its not related to actual issues in the software; instructions have been provided on preparing for running on testnet with the latest version.

**Comment by kangoala** [comment]
Just to mention that also after deleting all particl related folders (Particl, Particl Desktop Testnet, particl-market), and  a complete fresh installation (including a complete new sync), the marketplace still doesn't start (3 peers).
Market 0.3.3-alpha004
Core 0.19.2.12
Client: 3.0.0-RC-test004

**Comment by zaSmilingIdiot** [comment]
Have made contact with you offline already - some additional log info would be useful but this can be provided offline.
